### ISSUE TITLE
Los recursos deben tener nombre en plural

### ISSUE THREAD

**Issue by JJ** [antoniocuadros/WhenToClass#103]
Sería `grados`, no `grado`. Lee la guía de buenas prácticas en el material de la asignatura.

**Comment by antoniocuadros** [comment]
Yo lo que hago es que cuando añado un solo grado lo hago a la ruta /grado/... y cuando quiero consultar los grados lo hago a /grados/... y si quiero consultar un solo grado lo hago a /grado/... Esto no es correcto?

**Comment by antoniocuadros** [comment]
Voy a cambiarlo, gracias
